export const ASSIGNMENT_GET_FAIL='ASSIGNMENT_GET_FAIL'
export const ASSIGNMENT_GET_SUCCESS = 'ASSIGNMENT_GET_SUCCESS'
export const ASSIGNMENT_GET_REQUEST= 'ASSIGNMENT_GET_REQUEST'


export const ASSIGNMENT_CREATE_REQUEST = "ASSIGNMENT_CREATE_REQUEST";
export const ASSIGNMENT_CREATE_SUCCESS = "ASSIGNMENT_CREATE_SUCCESS";
export const ASSIGNMENT_CREATE_FAIL = "ASSIGNMENT_CREATE_FAIL";

export const ASSIGNMENT_UPDATE_REQUEST = "ASSIGNMENT_UPDATE_REQUEST";
export const ASSIGNMENT_UPDATE_SUCCESS = "ASSIGNMENT_UPDATE_SUCCESS";
export const ASSIGNMENT_UPDATE_FAIL = "ASSIGNMENT_UPDATE_FAIL";

export const ASSIGNMENT_DELETE_REQUEST = "ASSIGNMENT_DELETE_REQUEST";
export const ASSIGNMENT_DELETE_SUCCESS = "ASSIGNMENT_DELETE_SUCCESS";
export const ASSIGNMENT_DELETE_FAIL = "ASSIGNMENT_DELETE_FAIL";



